version: '3.7'

services:
  demo-web:
    image: js.hangfire/demo-web:latest
    container_name: demo-web
    hostname: demo-web
    build:
      context: ../../
      dockerfile: src/JS.Hangfire.Demo.Web/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=d55e63d5-6dcf-48cd-884a-1b8b90c9b97a
      - App__SelfUrl=https://localhost:44353
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://demo-web
      - App__HealthCheckUrl=http://demo-web/health-status      
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Demo;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44353:443"
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  

  
  db-migrator:
    image: js.hangfire/demo-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Demo.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__Demo_Web__RootUrl=https://localhost:44353
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Demo;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  sqldata:
    name: demo_sqldata
networks:
  abp-network:
    name: demo-network
    driver: bridge